export function SampleVisual({kind}){
 if(kind==='calendar')return <div className="mock cal"><div className="mockbar">September Schedule</div><div className="week">{['SUN','MON','TUE','WED','THU','FRI','SAT'].map(x=><b key={x}>{x}</b>)}</div><div className="days">{Array.from({length:35},(_,i)=><span key={i} className={[3,5,9,11,16,18,23,25,30].includes(i)?'busy':''}>{i<2?'':i-1}</span>)}</div></div>;
 if(kind==='canva')return <div className="mock posters"><div className="poster city">BUDAPEST<small>Experience the city like a local</small></div><div className="poster light">FIND LIGHT<small>even in quiet places</small></div><div className="poster retail">FASHION<small>visual content practice</small></div></div>;
 if(kind==='apex')return <div className="mock apex"><aside>APEX<small>MODULES</small><i/><i/><i/></aside><section><span/><b>APEX</b><small>AI COMPANION CONCEPT</small></section><aside>STATUS<small>LOCAL-FIRST</small><i/><i/></aside></div>;
 if(kind==='process')return <div className="mock process"><h4>DELIVERY SERVICE WORKFLOW</h4><div className="flow"><span>Receive order</span><b>→</b><span>Verify details</span><b>→</b><span>Plan route</span><b>→</b><span>Deliver</span></div><p><em>Responsibility</em><strong>Accuracy & customer coordination</strong></p><p><em>Tools</em><strong>Mobile app • navigation • status updates</strong></p></div>;
 const headers=kind==='inventory'?['ITEM','STOCK','REORDER','SUPPLIER','STATUS']:kind==='orders'?['ORDER','CUSTOMER','AREA','TOTAL','STATUS']:kind==='tasks'?['TASK','PRIORITY','START','END','STATUS']:['TASK','OWNER','DEADLINE','PRIORITY','STATUS'];
 const rows=kind==='inventory'?[['Office Paper','84','20','Supplier A','OK'],['Printer Ink','12','15','Supplier B','REORDER'],['Folders','55','20','Supplier C','OK']]:kind==='orders'?[['ORD-1001','Sample A','North','1,250','Completed'],['ORD-1002','Sample B','Central','980','In Transit'],['ORD-1003','Sample C','South','1,460','Pending']]:[['Update tracker','Admin','Today','High','Done'],['Client follow-up','Support','2:00 PM','High','In Progress'],['File organization','Admin','4:00 PM','Medium','Pending']];
 const title=kind==='inventory'?'Inventory Coordination':kind==='orders'?'Order & Delivery Tracker':kind==='tasks'?'VA Services & Task Sheet':'Weekly Administrative Dashboard';
 return <div className="mock table"><div className="mockbar">{title}</div><div className="stats"><span><b>24</b>Tasks</span><span><b>18</b>Complete</span><span><b>4</b>In Progress</span><span><b>2</b>Pending</span></div><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>;
}
