'use client';
import {useEffect,useState} from 'react';
import {email,linkedin,projects,services,skills} from './data';
import {SampleVisual} from './components/Samples';
const Arrow=()=> <svg viewBox="0 0 24 24"><path d="M5 12h14M13 6l6 6-6 6"/></svg>;
export default function Home(){
 const [active,setActive]=useState(null),[copied,setCopied]=useState(false);
 useEffect(()=>{const k=e=>e.key==='Escape'&&setActive(null);addEventListener('keydown',k);return()=>removeEventListener('keydown',k)},[]);
 async function copy(){try{await navigator.clipboard.writeText(email);setCopied(true);setTimeout(()=>setCopied(false),1500)}catch{location.href=`mailto:${email}`}}
 return <main>
  <header><nav className="shell"><a className="brand" href="#top"><span>AC</span><b>Ananias.</b></a><div className="navlinks"><a href="#work">Work</a><a href="#skills">Skills</a><a href="#experience">Experience</a><a href="#contact">Contact</a></div><a className="pill" href={linkedin} target="_blank">LinkedIn <Arrow/></a></nav></header>
  <section id="top" className="hero shell"><div><p className="eyebrow">● Open to remote opportunities</p><h1>Helping business owners <em>stay organized.</em></h1><p className="lead">I&apos;m <strong>Ananias Jr. D. Catangui</strong>, an entry-level General Administrative Virtual Assistant focused on dependable support, accurate data handling, organized workflows, and continuous learning.</p><div className="actions"><a className="primary" href="#work">Explore my work <Arrow/></a><a className="ghost" href={linkedin} target="_blank">LinkedIn</a><button className="ghost" onClick={copy}>{copied?'Email copied!':'Copy email'}</button></div><div className="meta"><span>Philippines</span><span>Admin • Data • Support</span><span>Long-term remote role</span></div></div><div className="portrait"><div className="ring"/><img src="https://ananias-va-portfolio.vercel.app/ananias-profile.webp" alt="Ananias Jr. D. Catangui"/><small>GENERAL VA • Reliable • Adaptable</small></div></section>
  <div className="ticker">{[...skills,...skills].map((s,i)=><span key={i}>{s} ✦</span>)}</div>
  <section className="section shell split"><div><p className="kicker">01 / About me</p><h2>New to VA work.<br/><em>Not new to responsibility.</em></h2></div><div className="copy"><p>I&apos;m building my remote administrative career using discipline and practical skills developed through logistics, customer service, inventory, technical work, documentation, and independent field work.</p><p>I practice with productivity tools and administrative workflows, and I&apos;m also developing workflow-automation skills with <strong>n8n</strong> through personal projects. I&apos;m looking for a team where I can learn the process, contribute consistently, and grow long term.</p></div></section>
  <section className="section shell"><p className="kicker">02 / What I can support</p><h2>Practical help for <em>busy workflows.</em></h2><div className="services">{services.map((x,i)=><article key={x[0]}><small>0{i+1}</small><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section>
  <section id="work" className="section shell"><p className="kicker">03 / Selected work</p><h2>Click a project to <em>see the sample.</em></h2><p className="note">Self-directed practice and personal projects. No paid client work is claimed.</p><div className="projects">{projects.map((p,i)=><button className={i===7?'card featured':'card'} key={p[1]} onClick={()=>setActive(p)}><div className="cardtop"><span>{p[0]}</span><span>{p[2]}</span></div><div className="preview"><SampleVisual kind={p[5]}/><i>View sample <Arrow/></i></div><div className="cardcopy"><h3>{p[1]}</h3><p>{p[3]}</p><div>{p[4].map(t=><span key={t}>{t}</span>)}</div></div></button>)}</div></section>
  <section id="skills" className="section shell"><p className="kicker">04 / Toolkit</p><h2>Tools I use and <em>continue learning.</em></h2><div className="chips">{skills.map(s=><span key={s}>{s}</span>)}</div><p className="n8n"><strong>n8n:</strong> workflow-automation practice from personal projects, not professional client experience.</p></section>
  <section id="experience" className="section shell split"><div><p className="kicker">05 / Experience</p><h2>Transferable experience,<br/><em>ready for remote work.</em></h2></div><div className="timeline"><article><small>2022 - Present</small><h3>Foodpanda Delivery Rider</h3><p>Daily independent work involving navigation, customer coordination, time-sensitive tasks, payments, and accurate order handling.</p></article><article><small>Previous Experience</small><h3>Sales • Receiving & Dispatch • E-bike Technician • Deck Cadet</h3><p>Transferable strengths in customer service, responsibility, documentation, inventory, troubleshooting, adaptability, and work under pressure.</p></article></div></section>
  <section id="contact" className="section shell"><div className="contact"><p className="kicker">06 / Let&apos;s connect</p><h2>Need an organized extra pair of hands?</h2><p>I&apos;m ready to learn your workflow and help keep important details under control.</p><div className="actions"><a className="primary dark" href={`mailto:${email}`}>Email me <Arrow/></a><a className="ghost darkg" href={linkedin} target="_blank">LinkedIn profile</a></div></div></section>
  <footer className="shell"><span>© Ananias Jr. D. Catangui • General Administrative VA • Philippines</span><a href={linkedin} target="_blank">LinkedIn</a></footer>
  {active&&<div className="modal" onMouseDown={e=>e.target===e.currentTarget&&setActive(null)}><div className="dialog"><button className="close" onClick={()=>setActive(null)}>×</button><p className="kicker">{active[2]}</p><h2>{active[1]}</h2><p className="note">{active[3]}</p><div className="bigmock"><SampleVisual kind={active[5]}/></div></div></div>}
 </main>
}
