'use client';

const jobs=[
 ['Foodpanda Delivery Rider','Foodpanda Philippines | June 10, 2022 – Present',['Manage daily delivery schedules and route priorities while working independently in a time-sensitive environment.','Verify orders, addresses, customer instructions, and payment details to maintain accuracy and minimize errors.','Use mobile navigation and delivery applications to coordinate routes, status updates, and customer communication.','Handle cash and digital payments responsibly while providing professional customer service.']],
 ['Sales Demonstrator','Rusty Lopez – SM Megamall | Dec. 1, 2017 – Feb. 1, 2018',['Assisted customers with product inquiries, recommendations, and purchase decisions.','Maintained organized merchandise displays, monitored stock availability, and supported replenishment.']],
 ['Receiving & Dispatching Unit','Free Choice Mart | May 5, 2017 – Oct. 20, 2017',['Received, checked, documented, and organized incoming deliveries and inventory records.','Performed stock counts, identified discrepancies, and supported accurate replenishment.']],
 ['E-Bike Technician','Romai Electric Bike | Oct. 28, 2015 – Apr. 29, 2016',['Diagnosed and repaired electrical and mechanical issues across multiple e-bike models.','Maintained repair records, tools, spare parts, and customer service updates.']],
 ['Deck Cadet','M/V Star Ferry III | Oct. 8, 2014 – Oct. 15, 2015',['Supported vessel operations, watchkeeping, documentation, and safety procedures in a demanding environment.']],
 ['Stockman','Rusty Lopez – Iriga City | June 8, 2013 – Dec. 8, 2013',['Supported stock organization, inventory handling, replenishment, and accurate product placement.']]
];

export default function ResumePage(){return <main className="resume-page"><div className="resume-actions no-print"><a href="/">← Portfolio</a><button onClick={()=>window.print()}>Print / Save as PDF</button></div><article className="resume-sheet"><header className="resume-header"><p className="resume-kicker">ENTRY-LEVEL GENERAL ADMINISTRATIVE VIRTUAL ASSISTANT</p><h1>Ananias Jr. D. Catangui</h1><div className="resume-contact"><span>Iriga City, Camarines Sur, Philippines</span><span>+63 938 911 4841</span><a href="mailto:acatanguijr29@gmail.com">acatanguijr29@gmail.com</a><a href="https://www.linkedin.com/in/ananias-jr-catangui-7b424a129" target="_blank" rel="noreferrer">LinkedIn</a></div></header>
<section><h2>Professional Profile</h2><p>Entry-level General Administrative Virtual Assistant candidate with no previous professional VA work experience. Currently building practical knowledge through self-study and hands-on practice in administrative workflows, data entry, file organization, internet research, email and calendar basics, digital productivity tools, Canva, ChatGPT, and workflow automation concepts. Brings several years of transferable experience from logistics, retail, customer service, technical service, inventory, and documentation, including working independently, meeting deadlines, maintaining accuracy, and assisting customers.</p></section>
<section><h2>Foundational VA Knowledge & Transferable Strengths</h2><p className="resume-tags">Administrative Support Basics • Data Entry • File Organization • Internet Research • Email & Calendar Workflow Basics • Documentation • Customer Service • Schedule Management • Record Accuracy • Inventory Coordination • Problem Solving • Independent Work</p></section>
<section><h2>Tools — Learning & Practice Level</h2><p className="resume-tags">Microsoft Office • Google Workspace • Google Sheets • Google Calendar • Canva • ChatGPT • Monday.com • n8n (workflow practice) • ElevenLabs • Ideogram • Fliki • Python (beginner / personal project use)</p></section>
<section><h2>Practice Projects & Self-Directed Learning</h2><div className="resume-project"><h3>General VA Sample Work Pack</h3><p>Self-created practice — not professional client work</p><ul><li>Created practical samples for email management, scheduling, meeting minutes, internet research, travel planning, file organization, customer support, SOPs, task tracking, and responsible AI-assisted administration.</li><li>Created an order tracker/dashboard practice sample and Canva design samples to demonstrate organization, presentation, and digital-content skills.</li></ul></div><div className="resume-project"><h3>APEX Personal AI Companion</h3><p>Ongoing personal learning project — not professional development experience</p><ul><li>Using ChatGPT, coding assistance, and beginner-level Python while learning interface planning, feature documentation, workflow ideas, testing, and troubleshooting.</li></ul></div><div className="resume-project"><h3>n8n Workflow Automation Practice</h3><p>Learning project</p><ul><li>Exploring triggers, prompt-generation steps, wait/status checks, file handling, and repeatable workflow logic without claiming professional automation experience.</li></ul></div></section>
<section><h2>Professional Experience</h2>{jobs.map(([role,meta,bullets])=><div className="resume-job" key={role}><div><h3>{role}</h3><p>{meta}</p></div><ul>{bullets.map(b=><li key={b}>{b}</li>)}</ul></div>)}</section>
<section className="resume-bottom-grid"><div><h2>Education</h2><p><strong>Bachelor of Science in Marine Transportation (BSMT)</strong></p></div><div><h2>Languages</h2><p>Filipino — Native<br/>English — Intermediate / Working Proficiency</p></div></section></article></main>}
